### ISSUE TITLE
Getting NullReferenceException

### ISSUE THREAD

**Issue by bzuillsmith** [froque/VSIXInteropFormsToolkit#4]
In VS 2017 I get a NullReferenceExcception on line 144 of GenerateInteropFormCommand.cs. It generates a single file for me and then throws this error which causes it not to process any other files.

**Comment by froque** [comment]
I am afraid that is not sufficient information for me to help. Care to share some code, stack trace or something more?

I am using Visual Studio 2015, but some of my colleagues are on Visual Studio 2017 with no complaints.

**Comment by bzuillsmith** [comment]
It may be related to the fact that I have some WiX projects that are not typical VS Projects with an assembly. I added ```if(currentAssembly == null || currentAssembly.CodeModel == null) return;``` and it worked. I could submit a PR if you like.

**Comment by froque** [comment]
yes, please do submit a PR
